version: "3.9"

services:
  # Base de données graphe
  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # UI
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=none
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./data/neo4j:/data
      - ./schema/neo4j-schema.cypher:/docker-entrypoint-initdb.d/schema.cypher
